---
title: "Survey Analysis 1"
output: html_notebook
---


```{r}
library(readr)
library(dplyr)
library(tidyr)
library(here)
post_data <- read_delim("C:/Users/Micah Allen/Google Drive/ECG_root/Projects/in_progress/Domain_General_Metacognition/COBE_LAB/data/final_survey/post_test_final.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

pre_data <- read_delim("C:/Users/Micah Allen/Google Drive/ECG_root/Projects/in_progress/Domain_General_Metacognition/COBE_LAB/data/final_survey/pre_test_final.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)


mle_data <- read_csv("MLE_TEST_summary.csv")

post_data <- post_data %>%
  rename(
    mem_belief_post = mem_belief,
    vis_belief_post = vis_belief,
    food_belief_post = food_belief,
    gdp_belief_post = gdp_belief
    )

pre_data <- pre_data %>%
  rename(
    mem_belief_pre = mem_belief,
    vis_belief_pre = vis_belief,
    food_belief_pre = food_belief,
    gdp_belief_pre = gdp_belief
    )

mle_data <- mle_data %>%
  rename(
    sID =subject
  )

all_data <- full_join(pre_data, post_data, by = "sID")

all_data <- full_join(all_data, mle_data, by = "sID")


all_data_trim <- all_data %>%
  mutate(mem_belief_diff = mem_belief_post - mem_belief_pre) %>%
  mutate(vis_belief_diff = vis_belief_post - vis_belief_pre) %>%
  mutate(food_belief_diff =food_belief_post - food_belief_pre) %>%
  mutate(gdp_belief_diff = gdp_belief_post - gdp_belief_pre) %>%
  select(-c("notes", "validation.x","validation.y")) %>%
  na.omit()



mw_data <- all_data_trim %>%
  select(56:84)


```


```{r}

library(psych)
library(RColorBrewer)

coul <- colorRampPalette(brewer.pal(8, "RdYlBu"))(25)


pdf("parallel_mw.pdf")
fa.parallel(mw_data)
dev.off()

fa_mw <- fa(mw_data, nfactors = 5, rotate= "varimax", scores = "regression")

weights <- fa_mw$weights


#weights[weights < 0.01] = NaN


pdf("heatmap_mw.pdf")
heatmap(as.matrix(weights), scale = "column")#, Rowv = NA, Colv = NA)
dev.off()

scores_mw<-as.data.frame(fa_mw$scores)
scores_mw$sID <- all_data_trim$sID

pdf("factor_plot_mw.pdf")
fa.plot(fa_mw)
dev.off()


pdf("diagram_mw.pdf")
fa.diagram(fa_mw)
dev.off()


all_data_trim <- full_join(all_data_trim, scores_mw, by = "sID")

write.csv(all_data_trim, "all_data_MLE_MW.csv")
```


```{r}
ggplot(fit_data, aes(x = modality, y = da, fill = modality)) +
  geom_violin(trim = TRUE) +
  geom_boxplot(width = .2, outlier.shape = NA) +
  scale_fill_brewer(palette = 3)+
  ylim(0,3)+
  theme_cowplot()
ggsave("dprime_Violin.jpeg", height = 4, width = 6)


```

