Set-up. 

```{r}
#update.packages(ask = FALSE, checkBuilt = TRUE)

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(ez)
library(emmeans)
library(afex)
library(ggpol)


metacognition_data <- read_csv("C:/Users/Micah Allen/Google Drive/ECG_root/Projects/in_progress/VMP_cohort_1/data/summary_data/Trivia_All_Data.csv")

Absolute_Directory <- dirname(rstudioapi::getSourceEditorContext()$path)

setwd(Absolute_Directory)
getwd()
View(metacognition_data_master)

metacognition_data$modality <- as.factor(metacognition_data$modality)

head(metacognition_data)

metadata <- na.omit(metacognition_data)

metadata <- tbl_df(metadata)

glimpse(metadata)

```


```{r}

remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}


```

Filter data for outlier RTs and Conf Rts
```{r}

# Apply the finction to one column

clean_data = metacognition_data %>%
  tbl_df() %>%
  group_by(subject, modality) %>%
  drop_na()%>%
#  filter(trial > 50) %>%
#  filter(contrast != 30) %>%
  filter(rt > 0.05) %>%
  filter(rt_conf > 0.05) %>%    
  mutate_at(vars(rt, rt_conf, contrast), funs(remove_outliers)) %>%
  drop_na()


```



Plot confidence

```{r}

clean_data %>% 
  group_by(subject, modality) %>%
  summarise(mean = mean(confidence), var = var(confidence), n = n())%>%
  ggplot(., aes(x = modality, y = mean, fill = modality)) +
  geom_violin() +
  theme_cowplot() + 
  ylab("Mean Confidence") +
  geom_boxplot(width = .1)
  

```

plot median RT
```{r}

clean_data %>% 
  group_by(subject, modality) %>%
  summarise(median = median(rt), var = var(rt), n = n())%>%
  ggplot(., aes(x = modality, y = median, fill = modality)) +
  geom_violin() +
  geom_boxplot(width = .1)+
  ylab("Median RT") +
  theme_cowplot()
  

```

plot mean accuracy 
```{r}

clean_data %>% 
  group_by(subject, modality) %>%
  summarise(mean = mean(accuracy), var = var(accuracy), n = n())%>%
  ggplot(., aes(x = modality, y = mean, fill = modality)) +
  geom_violin() +
  ylim(0,1) +
  geom_boxplot(width = .1) +
  ylab("Mean Accuracy")+
  theme_cowplot()
  


ggsave(path = getwd(),filename = "accuracy.png", device = "png", dpi = 600,
       width = 12, height = 8, units = "cm") 

```

plot median rt confidence

```{r}

clean_data %>% 
  group_by(subject, modality) %>%
  summarise(median = median(rt_conf), var = var(rt_conf), n = n())%>%
  ggplot(., aes(x = modality, y = median, fill = modality)) +
  geom_violin() +
  geom_boxplot(width = .1) +
  ylab("Median Confidence RT")+
  theme_cowplot()
  



```
Plot single conditions
```{r}

clean_data %>%
  filter(modality == "Calories") %>%
  group_by(subject, modality) %>%
  summarise(median = median(contrast), var = var(contrast), n = n())%>%
  ggplot(., aes(x = modality, y = median, fill = modality)) +
  geom_violin() +
  geom_boxplot(width = .1) +
  ylab("Median Contrast")+
  theme_cowplot()
  


clean_data %>%
  filter(modality == "GDP") %>%
  #mutate(contrast = exp(contrast)) %>%
  group_by(subject, modality) %>%
  summarise(median = median(contrast), var = var(contrast), n = n())%>%
  ggplot(., aes(x = modality, y = median, fill = modality)) +
  geom_violin() +
  geom_boxplot(width = .1) +
  ylab("Median Contrast")+
  theme_cowplot()



clean_data %>%
  filter(modality == "vision") %>%
  group_by(subject, modality) %>%
  summarise(median = median(contrast), var = var(contrast), n = n())%>%
  ggplot(., aes(x = modality, y = median, fill = modality)) +
  geom_violin() +
  geom_boxplot(width = .1) +
  ylab("Median Contrast")+
  theme_cowplot()


```

Fit models
```{r}


conf_model = aov_ez(data = clean_data, id = "subject", dv = "confidence", within = c("accuracy", "modality"))
print(conf_model)

afex_plot(conf_model, x = "modality", trace = "accuracy", error = "within")



```

Plot the ANOVA
```{r}

afex_plot(conf_model, x = "modality", trace = "accuracy", error = "within",
 mapping = c("shape", "fill"), dodge = 0.7,
          data_geom = ggpol::geom_boxjitter, 
          data_arg = list(
            width = 0.5,
            jitter.color = "gray",
            jitter.width = 0.1,
            jitter.height = 0,
            outlier.color = "gray",
            outlier.intersect = TRUE),
          point_arg = list(size = 2.5), 
          error_arg = list(size = 1.5, width = 0),
          factor_levels = list(modality = c("Nutritional", "Economic", "Memory", "Visual"),
                               accuracy = c("Correct", "Incorrect")), 
          legend_title = "Decision Accuracy") +
  labs(y = "Average Confidence", x = "Decision Modality") +
  scale_y_continuous(breaks=seq(1, 7, length.out = 7)) +
  scale_fill_manual(values=c("green", "red"))+
  theme_bw(base_size = 15) + 
  theme(legend.position="bottom", panel.grid.major.x = element_blank())

ggsave(path = getwd(),filename = "conf_acc_modal1.png", device = "png", dpi = 600,
       width = 12, height = 8, units = "cm") 
```

```{r}
rt_model = aov_ez(data = clean_data, id = "subject", dv = "rt", within = c("accuracy", "modality"), fun_aggregate = median)
print(model)
```

```{r}
afex_plot(rt_model, x = "modality", trace = "accuracy", error = "within",
 mapping = c("shape", "fill"), dodge = 0.7,
          data_geom = ggpol::geom_boxjitter, 
          data_arg = list(
            width = 0.5,
            jitter.color = "gray",
            jitter.width = 0.1,
            jitter.height = 0,
            outlier.color = "gray",
            outlier.intersect = TRUE),
          point_arg = list(size = 2.5), 
          error_arg = list(size = 1.5, width = 0),
          factor_levels = list(modality = c("Calories", "GDP", "Memory", "Vision"),
                               accuracy = c("Correct", "Incorrect")), 
          legend_title = "Accuracy") +
  labs(y = "Reaction Time", x = "Modality") +
 # scale_y_continuous(breaks=seq(1, 7, length.out = 7)) +
  theme_bw(base_size = 15) + 
  theme(legend.position="bottom", panel.grid.major.x = element_blank())


```


```{r}
conf_rt_model = aov_ez(data = clean_data, id = "subject", dv = "rt_conf", within = c("accuracy", "modality"), fun_aggregate = median)
print(conf_rt_model)


afex_plot(conf_rt_model, x = "modality", trace = "accuracy", error = "within",
 mapping = c("shape", "fill"), dodge = 0.7,
          data_geom = ggpol::geom_boxjitter, 
          data_arg = list(
            width = 0.5,
            jitter.color = "gray",
            jitter.width = 0.1,
            jitter.height = 0,
            outlier.color = "gray",
            outlier.intersect = TRUE),
          point_arg = list(size = 2.5), 
          error_arg = list(size = 1.5, width = 0),
          factor_levels = list(modality = c("Calories", "GDP", "Memory", "Vision"),
                               accuracy = c("Correct", "Incorrect")), 
          legend_title = "Accuracy") +
  labs(y = "CReaction Time", x = "Modality") +
 # scale_y_continuous(breaks=seq(1, 7, length.out = 7)) +
  theme_bw(base_size = 15) + 
  theme(legend.position="bottom", panel.grid.major.x = element_blank())


```

```{r}
acc_rt_model = aov_ez(data = clean_data, id = "subject", dv = "accuracy", within = c("modality"), fun_aggregate = mean)
print(conf_rt_model)


afex_plot(acc_rt_model, x = "modality", error = "within",
 mapping = c("shape", "fill"), dodge = 0.7,
          data_geom = ggpol::geom_boxjitter, 
          data_arg = list(
            width = 0.5,
            jitter.color = "gray",
            jitter.width = 0.1,
            jitter.height = 0,
            outlier.color = "gray",
            outlier.intersect = TRUE),
          point_arg = list(size = 2.5), 
          error_arg = list(size = 1.5, width = 0),
          factor_levels = list(modality = c("Calories", "GDP", "Memory", "Vision")),
          legend_title = "Accuracy") +
  labs(y = "CReaction Time", x = "Modality") +
 # scale_y_continuous(breaks=seq(1, 7, length.out = 7)) +
  theme_bw(base_size = 15) + 
  theme(legend.position="bottom", panel.grid.major.x = element_blank())


```


