%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Micah Allen\Google Drive\ECG_root\Projects\in_progress\Domain_General_Metacognition\COBE_LAB\data_master.xlsx
%    Worksheet: data_master
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/03/05 21:58:17

%% Import the data
% If Micah is running it, uncomment
%[~, ~, raw] = xlsread('C:\Users\Micah Allen\Google Drive\ECG_root\Projects\in_progress\Domain_General_Metacognition\COBE_LAB\data_master.xlsx','data_master','A2:F332');
%If Camile is running it
[~, ~, raw] = xlsread('C:\Users\Camile Correa\Google Drive\ECG_root\Projects\in_progress\Domain_General_Metacognition\COBE_LAB\data_master.xlsx','data_master','A2:F332');

stringVectors = string(raw(:,[3,5]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,2,4,6]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
datamaster = table;

%% Allocate imported array to column variable names
datamaster.sID = data(:,1);
datamaster.exclude = data(:,2);
datamaster.task_order = categorical(stringVectors(:,1));
datamaster.Age = data(:,3);
datamaster.Gender = categorical(stringVectors(:,2));
datamaster.YearsEdu = data(:,4);

%% Clear temporary variables
clearvars data raw stringVectors;