%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Micah Allen\Google Drive\ECG_root\Projects\in_progress\Domain_General_Metacognition\COBE_LAB\data\testing\data_master_test.xlsx
%    Worksheet: data_master_test
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/03/02 18:14:32

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Micah Allen\Google Drive\ECG_root\Projects\in_progress\Domain_General_Metacognition\COBE_LAB\data\testing\data_master_test.xlsx','data_master_test');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,5));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
datamastertest = table;

%% Allocate imported array to column variable names
datamastertest.sID = data(:,1);
datamastertest.validation = data(:,2);
datamastertest.exclude = data(:,3);
datamastertest.Age = data(:,4);
datamastertest.Gender = categorical(stringVectors(:,1));
datamastertest.YearsEdu = data(:,5);
datamastertest.mem1 = data(:,6);
datamastertest.vis1 = data(:,7);
datamastertest.food1 = data(:,8);
datamastertest.gdp1 = data(:,9);
datamastertest.mw1 = data(:,10);
datamastertest.mw2 = data(:,11);
datamastertest.mw3 = data(:,12);
datamastertest.mw4 = data(:,13);
datamastertest.mw5 = data(:,14);
datamastertest.mw6 = data(:,15);
datamastertest.mw7 = data(:,16);
datamastertest.mw8 = data(:,17);
datamastertest.mw9 = data(:,18);
datamastertest.mw10 = data(:,19);
datamastertest.mw11 = data(:,20);
datamastertest.mw12 = data(:,21);
datamastertest.mw13 = data(:,22);
datamastertest.mw14 = data(:,23);
datamastertest.mw15 = data(:,24);
datamastertest.mw16 = data(:,25);
datamastertest.mw17 = data(:,26);
datamastertest.mw18 = data(:,27);
datamastertest.mw19 = data(:,28);
datamastertest.mw20 = data(:,29);
datamastertest.mw21 = data(:,30);
datamastertest.mw22 = data(:,31);
datamastertest.mw23 = data(:,32);
datamastertest.mw24 = data(:,33);
datamastertest.mw25 = data(:,34);
datamastertest.mw26 = data(:,35);
datamastertest.mw27 = data(:,36);
datamastertest.mw28 = data(:,37);
datamastertest.mw29 = data(:,38);
datamastertest.mw30 = data(:,39);
datamastertest.mw31 = data(:,40);
datamastertest.mw32 = data(:,41);
datamastertest.mw33 = data(:,42);
datamastertest.mw34 = data(:,43);
datamastertest.mw35 = data(:,44);
datamastertest.mw36 = data(:,45);
datamastertest.mw37 = data(:,46);

%% Clear temporary variables
clearvars data raw stringVectors R;