---
title: "Paper Wrapper: Domain General Metacognition"
output: html_notebook
---

Setup

```{r}
# clean slate to be sure
rm(list = ls())
source(here("r", "setup_depends.R"))
source(here("r", "bootcormat.R")) 

# set apa theme for plots
apatheme=theme_bw()+ #theme
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text = element_text(size = 15),
        axis.title = element_text(size = 12))



# spider-man color palette

colors = c("#DF1F2D", "#B11313", "#2B3784", "#447BBE")
```

Data import

```{r}

source(here("r", "metacog_data_import.R")) # imports data and runs trial level exclusions from the prereg. 

head(metadata)

```


Load or fit the MLE model (if it does not exist).

```{r}

subjects = unique(metadata$subject) # subjects vector, for looping
modalities = as.character(unique(metadata$modality)) # modalities vector, for looping


fit_filename = here("data_summary", "mle_fitdata.Rda")

if (file.exists(fit_filename) == 1 ) {

load(fit_filename)
  
}else  {
  
source(here("r", "fit_mle_loop.R"))

  }

head(mle_fit_data)
```

Run group level exclusions based on MLE. 

```{r}

# script to run all group level exclusions
source(here("r", "mle_fitdata_exclude.R")) 

# da plot
p1+p2
# c plot
p3+p4
# mratio plot
p5+p6

# median contrast

p7+p8



```

Pivot the MLE data frame to wide. 
```{r}


mle_wdata_exclude <- mle_metadata_exc %>% pivot_wider(
  names_from = modality,
  values_from = c(da, mda, mratio, c, avg_conf)
)


write.csv(mle_wdata_exclude, file = here("data_summary","mle_fit_data_wide.csv"))

head(mle_wdata_exclude)
```


Now run the bootstrapped Spearman's correlations, for preregistered hypothesis tests.

```{r}

# cognitive sensitivity - dprime

corrdat <- mle_wdata_exclude %>%
  na.omit() %>%
  select(starts_with("da"))

apa.bootcor.table(corrdat, filename=here("tables", "da_bootCorr_table.doc"))

# average confidence - metabias 

corrdat <- mle_wdata_exclude %>%
  na.omit() %>%
  select(starts_with("avg_conf"))

apa.bootcor.table(corrdat, filename=here("tables", "conf_bootCorr_table.doc"))

# metacognitive sensitivity 

corrdat <- mle_wdata_exclude %>%
  na.omit() %>%
  select(starts_with("mda"))

apa.bootcor.table(corrdat, filename=here("tables", "MDA_bootCorr_table.doc"))

# metacognitive efficiency
corrdat <- mle_wdata_exclude %>%
  na.omit() %>%
  select(starts_with("mratio"))

apa.bootcor.table(corrdat, filename=here("tables", "mratio_bootCorr_table.doc"))

#mda_results <- bootcormat(corrdat)



```

Next we will fit (or load) the hierarchical metacognition model 

```{r}
# these next lines will download the fitted model file from the project
# open science foundation (OSF) repository. Because the files are too large for github
# (around 250 mb), we download them to a local directory 

osf_project <- osf_retrieve_node("https://osf.io/u6sf2/")

download_path <- here("osf")
osf_files <- osf_ls_files(osf_project)

osf_download(osf_files, path = download_path)
```


```

