---
title: 'Supplementary Wrapper: Domain General Metacognition'
output:
  word_document: default
  html_notebook: default
---

Setup

```{r}
# clean slate to be sure
rm(list = ls())
if (!require("here")) install.packages("here")
source(here("r", "setup_depends.R"))
source(here("r", "bootcormat.R")) 

# set apa theme for plots
apatheme=theme_bw()+ #theme
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text = element_text(size = 15),
        axis.title = element_text(size = 12))

# spider-man color palette

colors = c("#DF1F2D", "#B11313", "#2B3784", "#447BBE")
```

Data import
```{r}

source(here("r", "metacog_data_import.R")) # imports data and runs trial level exclusions from the prereg. 

head(metadata)

```

Load or fit the MLE model (if it does not exist).

```{r}

subjects = unique(metadata$subject) # subjects vector, for looping
modalities = as.character(unique(metadata$modality)) # modalities vector, for looping


fit_filename = here("data_summary", "mle_fitdata.Rda")

if (file.exists(fit_filename) == 1 ) {

load(fit_filename)
  
}else  {
  
source(here("r", "fit_mle_loop.R"))

  }

head(mle_fit_data)
```

Run group level exclusions based on MLE and pivot: 
```{r}

# script to run all group level exclusions
source(here("r", "mle_fitdata_exclude.R")) 


```
1. The ANOVA and t-tests (post-hoc: Holm)
```{r}
#Script to run ANOVAs for the MLE
source(here("r", "Anova_2.R"))

```

1. Tables of The ANOVA and t-tests (post-hoc: Holm)
```{r}
#Script to produce tables for ANOVA and t-test. 
#This also produces cvs files of the tables which can be found in the folder "tables". 
source(here("r", "ANOVA_tables.R")) 

ANOT #ANOVAs
DTT #d' t-test
CTT #criterion t-test
MBTT #metacognitive bias t-test
MSTT #metacognitive sensivity t-test
METT #metacognitive efficiency t-test

```

2. Get the Bayes Factors from the correlations of the MLE model:
```{r}

fit_data_wide <- read_csv(here("data_summary", "mle_fit_data_wide.csv"))

source(here("r", "Bayesfactor.R")) 

#The tables of the Bayes Factor
BayesSen #Metacognitive Sensitivity
BayesEff #Metacognitive Efficiency
BayesBia #Metacognitive Bias
BayesCog #Dpime

```
3. The Split Half Analysis: MLE
```{r}

#Fit the Odd and even trials, exclude outliers and pivot:
source(here("r", "Splithalf_MLE.R")) 

#Estimate the correlations using the robust brostrapped correlations:
corrdatEven <- fit_data_wideEvenF %>%
  na.omit() %>%
  select(starts_with("Even_mratio"))

apa.bootcor.table(corrdatEven, filename=here("tables", "Even_bootCorr_table.doc"))

corrdatOdd <- fit_data_wideOddF %>%
  na.omit() %>%
  select(starts_with("Odd_mratio"))

apa.bootcor.table(corrdatOdd, filename=here("tables", "Odd_bootCorr_table.doc"))

```

Spilt Half Analysis: MLE - plots
```{r}
source(here("r", "Splithalf_MLE_tables.R")) 

comPlot1

```
Spli Half Analysis - HMeta-d'. 
This takes a long time! 
```{r}
source(here("r", "Splithalf_HMetad.R")) 
```


