```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(metaSDT)

metacognition_data <- read_csv("C:/Users/Micah Allen/Google Drive/ECG_root/Projects/in_progress/Domain_General_Metacognition/COBE_LAB/metacognition_data_master.csv")
View(metacognition_data_master)

metacognition_data$modality <- as.factor(metacognition_data$modality)

head(metacognition_data)

metadata <- na.omit(metacognition_data)

metadata <- tbl_df(metadata)



dt2 <- metadata %>%
  group_by(subject, modality) %>%
  mutate(rt = remove_outliers(rt))


dt2 <- na.omit(dt2)


dt2 %>%
  group_by(subject, modality) %>%
  mutate(rt = remove_outliers(rt_conf))


dt2 <- na.omit(dt2)


nrow(metadata)-nrow(dt2)

metadata<-dt2

glimpse(metadata)

```



```{r}

d1 <- filter(metadata, subject == 121 & modality == "GDP")

newlist <- trials2counts(d1$signal, d1$response,d1$confidence,7, padAmount = 1,padCells=1)

Absolute_Directory <- dirname(rstudioapi::getSourceEditorContext()$path)

setwd(Absolute_Directory)
getwd()


#Seperating output into vectors containing the total number of responses in
#each response category, conditional on presentation of S1 and S2.
nR_S1 <- unlist(newlist[1], recursive = TRUE, use.names = TRUE)
nR_S2 <- unlist(newlist[2], recursive = TRUE, use.names = TRUE)

# bayesian individual fit
fit1 <- metad_indiv(nR_S1 = nR_S1, nR_S2 = nR_S2)

# MLE fit
fit2 <- fit_meta_d_MLE(nR_S1, nR_S2)

# 'balance' fit
fit3 <- fit_meta_d_bal(nR_S1, nR_S2)

# sse fit 
fit4 <- fit_meta_d_SSE(nR_S1, nR_S2)

```

plot parameters from three fits

```{r}
obs <- data.frame("mratio" = rbind(fit1$mratio, fit2$M_ratio[1],fit3$meta_d_ratio[1], fit4$M_ratio[1]))
obs$fit_type <- c("Bayes", "MLE", "Bal", "SSE")

ggplot(obs, aes(x = fit_type, y = mratio)) +
  geom_point()

```

Let's try to loop

```{r}

Absolute_Directory <- dirname(rstudioapi::getSourceEditorContext()$path)

setwd(Absolute_Directory)
getwd()

subjects = unique(metadata$subject)
modalities = as.character(unique(metadata$modality))

fit_data = data.frame()

for(s in 1:length(subjects)) {
  
  
  for(m in 1:length(modalities)) {
    
    tryCatch(
      expr = {
        # subset data for subject and modality 
        subdata <- filter(metadata, subject == subjects[s] & modality == modalities[m])  
        
        #transform trial data to counts
        newlist <- trials2counts(subdata$signal, subdata$response, subdata$confidence,7, padAmount = 1,padCells=1)
        nR_S1 <- unlist(newlist[1], recursive = TRUE, use.names = TRUE)
        nR_S2 <- unlist(newlist[2], recursive = TRUE, use.names = TRUE)
        
        #fit model
        fit <- fit_meta_d_MLE(nR_S1, nR_S2)
        #glimpse(subdata)
        #Sys.sleep(1)
        
        output <- data.frame("subject" = subjects[s],"modality"=modalities[m],
                             "da" = fit$da[1], "mda" = fit$meta_da[1],
                             "mratio" = fit$M_ratio[1])  
        
        fit_data <- rbind(fit_data, output)
      },
      error = function(e) {
        message("* caught an error on subject ", subjects[s])
        print(e)
        output <- data.frame("subject" = subjects[s],
                             "modality"=modalities[m],"da" = NaN,
                             "mda" = NaN, "mratio" = NaN) 
        fit_data <- rbind(fit_data, output)
        
        }
      
      
    )
    
  }
  
}

write.csv(fit_data, file = "mle_mratio_fit_data.csv")
```

```{r}
head(fit_data)

plot_data <- filter(fit_data, mratio > 0)

plot_data <- plot_data %>%
  group_by(subject, modality) %>%
  mutate(da = remove_outliers(da))

plot_data <-  na.omit(plot_data)


plot_data <- plot_data %>%
  group_by(subject, modality) %>%
  mutate(mratio = remove_outliers(mratio))

plot_data <-  na.omit(plot_data)

ggplot(plot_data, aes(x = modality, y = mratio)) +
  geom_boxjitter()


model = aov_ez(data = plot_data, id = "subject", dv = "mratio", within = c("modality"))
print(model)
```

```{r}

library(ez)
library(emmeans)
library(afex)
library(ggpol)
library(ggbeeswarm)
afex_plot(model, x = "modality", error = "within")
```
```{r}
ggplot(plot_data, aes(x = modality, y = mratio, fill = modality)) +
  geom_violin() +
  geom_boxjitter(
            width = 0.5,
            jitter.color = "gray",
            jitter.width = 0.1,
            jitter.height = 0,
            outlier.color = "gray",
            outlier.intersect = TRUE)


```

```{r}
jasp_data <- plot_data
jasp_data <- pivot_wider(data = jasp_data, names_from = modality, values_from = c(da, mda, mratio)) 


write.csv(jasp_data, "M_Ratio_summary.csv")
```


loop and get bayes fit

```{r}

Absolute_Directory <- dirname(rstudioapi::getSourceEditorContext()$path)

setwd(Absolute_Directory)
getwd()

subjects = unique(metadata$subject)
modalities = as.character(unique(metadata$modality))

fit_data_bayes = data.frame()

for(s in 1:length(subjects)) {
  
  
  for(m in 1:length(modalities)) {
    
    tryCatch(
      expr = {
        # subset data for subject and modality 
        subdata <- filter(metadata, subject == subjects[s] & modality == modalities[m])  
        
        #transform trial data to counts
        newlist <- trials2counts(subdata$signal, subdata$response, subdata$confidence,7, padAmount = 0,padCells=1)
        nR_S1 <- unlist(newlist[1], recursive = TRUE, use.names = TRUE)
        nR_S2 <- unlist(newlist[2], recursive = TRUE, use.names = TRUE)
        
        #fit model
        fit <- metad_indiv(nR_S1, nR_S2)
        #glimpse(subdata)
        #Sys.sleep(1)
        
        output <- data.frame("subject" = subjects[s],"modality"=modalities[m],
                             "da" = fit$d, "mda" = fit$mean,
                             "mratio" = fit$mratio)  
        
        fit_data_bayes <- rbind(fit_data_bayes, output)
      },
      error = function(e) {
        message("* caught an error on subject ", subjects[s])
        print(e)
        output <- data.frame("subject" = subjects[s],
                             "modality"=modalities[m],"da" = NaN,
                             "mda" = NaN, "mratio" = NaN) 
        fit_data_bayes <- rbind(fit_data_bayes, output)
        
        }
      
      
    )
    
  }
  
}

write.csv(fit_data_bayes, file = "bayes_mratio_fit_data.csv")
```

```{r}
head(fit_data_bayes)

plot_data <- fit_data_bayes



plot_data <- filter(fit_data_bayes, mratio > 0)
plot_data <- filter(plot_data, da > 0)
plot_data <- filter(plot_data, mda > 0)



trim_data = plot_data %>%
  group_by(modality) %>%
  mutate_at(vars(da, mda, mratio), funs(remove_outliers))
  

ggplot(trim_data, aes(x = modality, y = mratio))+
  geom_boxplot()

jasp_data <- trim_data
jasp_data <- pivot_wider(data = jasp_data, names_from = modality, values_from = c(da, mda, mratio)) 


write.csv(jasp_data, "bayes_MR_summary.csv")


```

```{r}
remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}
```

