```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(ez)
library(emmeans)
library(afex)
library(ggpol)
#source(remove_outliers.R)
rm(list=ls())

#library(ggbeeswarm)

```

```{r}
metacognition_data <- read_csv("C:/Users/Micah Allen/Google Drive/ECG_root/Projects/in_progress/Domain_General_Metacognition/COBE_LAB/metacognition_data_master.csv")

Absolute_Directory <- dirname(rstudioapi::getSourceEditorContext()$path)

setwd(Absolute_Directory)
getwd()

```


trial level exclusions 

```{r}

clean_data = metacognition_data %>%
  group_by(subject, modality) %>%
  drop_na()%>%
#  filter(trial > 10) %>%
#  filter(subject != 1) %>%
#  filter(contrast != 30) %>%
  filter(rt > 0.05) %>%
  filter(rt_conf > 0.05) %>%    
  mutate_at(vars(rt, rt_conf), funs(remove_outliers)) %>%
  drop_na()


```

```{r}
subjects = unique(clean_data$subject)
modalities = as.character(unique(clean_data$modality))

fit_data = data.frame()

for(s in 1:length(subjects)) {
  
  
  for(m in 1:length(modalities)) {
    
    tryCatch(
      expr = {
        # subset data for subject and modality 
        subdata <- filter(clean_data, subject == subjects[s] & modality == modalities[m])  
        
        #transform trial data to counts
        newlist <- trials2counts(subdata$signal, subdata$response, subdata$confidence,7, padAmount = 1,padCells=1)
        nR_S1 <- unlist(newlist[1], recursive = TRUE, use.names = TRUE)
        nR_S2 <- unlist(newlist[2], recursive = TRUE, use.names = TRUE)
        
        #fit model
        fit <- fit_meta_d_MLE(nR_S1, nR_S2)
        #glimpse(subdata)
        #Sys.sleep(1)
        
        output <- data.frame("subject" = subjects[s],"modality"=modalities[m],
                             "da" = fit$da[1], "mda" = fit$meta_da[1],
                             "mratio" = fit$M_ratio[1])  
        
        fit_data <- rbind(fit_data, output)
      },
      error = function(e) {
        message("* caught an error on subject ", subjects[s])
        print(e)
        output <- data.frame("subject" = subjects[s],
                             "modality"=modalities[m],"da" = NaN,
                             "mda" = NaN, "mratio" = NaN) 
        fit_data <- rbind(fit_data, output)
        
        }
      
      
    )
    
  }
  
}

write.csv(fit_data, file = "mle_mratio_fit_data_3.csv")
```


```{r}
p1<-ggplot(fit_data, aes(x = modality, y = mratio))+
  geom_boxplot()


plot_data = fit_data %>%
  tbl_df() %>%
  group_by(modality) %>%
  filter(mratio > 0) %>%
  filter(da > 0) %>%
  filter(mda > 0) %>%
  mutate_at(vars(da, mratio), funs(remove_outliers)) %>%
  drop_na()

  
p2<-ggplot(plot_data, aes(x = modality, y = mratio))+
  geom_boxplot()

p1
p2

jasp_data <- plot_data

jasp_data <- pivot_wider(data = jasp_data, names_from = modality, values_from = c(da, mda, mratio)) 

jasp_data <- na.omit(jasp_data)



write.csv(jasp_data, "MLE_TEST_summary.csv")

```

