---
title: "AUROC_fit"
output: html_document
---
First setup: 

```{r}

# clean slate to be sure
rm(list = ls())

# check for pacman package and install if not found
if (!require("pacman")) install.packages("pacman")
pacman::p_load(afex, readr, dplyr, tidyr, ggplot2, cowplot, devtools, here, tidyverse, magrittr, reshape2, rjags, coda, lattice, ggmcmc, foreach, doParallel, ggpubr, ggpol, patchwork, ggcorrplot, ggstatsplot, GGally, BayesFactor, gridExtra, viridis, gghalves, gt, rstatix)


# load the metaSDT package from github
if (!require("metaSDT")) devtools::install_github("craddm/metaSDT")
# load Rousselet correlation package 
if (!require("bootcorci")) devtools::install_github("GRousselet/bootcorci")

source(here("r", "remove_outliers_robust.R"))
source(here("r", "outliers.R"))
source(here("r", "trials2counts.R"))
source(here("r", "metad_indiv.R"))
source(here("r", "fit_mle.R"))
source(here("r", "sdt_functions.R"))
source(here("r", "Function_metad_groupcorr.R"))
source(here("r", "BootCorci.R"))
source(here("r", "Function_scatterplot.R"))
source(here("r", "function_rhoPlot.R"))
source(here("r", "function_apa.R"))
source(here("r", "fitMLEEven.R"))
source(here("r", "fitMLEOdd.R"))
source(here("r", "function_rhoPlotSplit.R"))
source(here("r", "function_rhoPlotSplit.R"))
source(here("r", "Function_AUROC.R"))
# set apa theme for plots
apatheme=theme_bw()+ #theme
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text = element_text(size = 15),
        axis.title = element_text(size = 12))


# spider-man color palette

colors = c("#DF1F2D", "#B11313", "#2B3784", "#447BBE")



```

Then get the data

```{r}

# read in the data

metacognition_trial_data <- read_csv(here("data_summary", "metacognition_TrialData_master.csv"), 
    col_types = cols(confidence = col_double(), 
        rt_conf = col_double()))

# set modality as factor
metacognition_trial_data$modality <- as.factor(metacognition_trial_data$modality )

# remove any rows containing NaNs (i.e., missing data)

metacognition_trial_data <- na.omit(metacognition_trial_data)

head(metacognition_trial_data)



metadata <- metacognition_trial_data %>%
  group_by(subject, modality) %>%
  mutate(rt = remove_outliers_robust(rt)) # remove RT outliers using MAD Rule - SEE PRE REG

metadata <- na.omit(metadata)

#Exclude those with rt <50ms 
metadata <- metadata%>%filter(rt>=0.05) 


#Exclude those with less than 50% trials (i.e. less than 100 or 50) within condition
metadata<-metadata%>%mutate(modality=as.factor(modality))
metadatac<-metadata #create new dataframe
metadatac$modality <-fct_collapse (metadatac$modality, trivia = c("Calories", "GDP"))#combine the two trivia tasks in new dataframe
metadatac <- metadatac %>%
  group_by(subject, modality)%>% count(subject) #count number of trials
excD <- subset(metadatac, metadatac$n<100) 
excID <-unique(excD$subject) #Identify participants for exclusion
metadata <- subset(metadata, !is.element(metadata$subject, excID)) ##Exclude IDs from that vector in original dataframe


```
The half-split analysis: 
```{r}
metadataEven <-metadata %>% filter(trial %% 2==0) %>% mutate(TrialType = "Even")
metadataOdd <- metadata %>% filter(trial %% 2!=0) %>% mutate (TrialType = "Odd")

#Bind the two dataframes: 
metadata <- rbind(metadataEven, metadataOdd)

```

Fit the data: each pair at the time. 
This takes a LONG TIME. 
```{r}
subjects = unique(metadataOdd$subject)

#corrects = accuracy
#subjectiveRatings=confidence
#NumRatings= 7
#Memory
outputMO=list()
  nR_S1_tmp_modality = data.frame((matrix(NA, nrow=14, ncol=319)))

  for (s in 1:length(subjects)){
    outputMO [s]= auroc2(metadataOdd$accuracy, metadataOdd$confidence, 7)
    
  }


calculate_auroc2 <- function(corrects, subjectiveRatings, numRatings)

outputM <- metad_groupcorr(nR_S1[[1]], nR_S2[[1]])
saveRDS(outputM, file = here("data_summary","Split_Mem.rds"))
#Calories
outputC <- metad_groupcorr(nR_S1[[2]], nR_S2[[2]])
saveRDS(outputC, file = here("data_summary","Split_Cal.rds"))
#GDP
outputG <- metad_groupcorr(nR_S1[[3]], nR_S2[[3]])
saveRDS(outputG, file = here("data_summary","Split_GDP.rds"))
#Vision
outputV <- metad_groupcorr(nR_S1[[4]], nR_S2[[4]])
saveRDS(outputV, file = here("data_summary","Split_Vis.rds"))


```

Correlate: 
